@URL = http://localhost:5000

### 1. Login as ADMIN
POST {{URL}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}

### 2. Login as USER  
POST {{URL}}/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password123"
}

### 3. Register a NEW USER
POST {{URL}}/auth/register
Content-Type: application/json

{
  "username": "student",
  "email": "student@university.edu",
  "password": "mypassword123"
}

### === Copy your token here after login ===
@ADMIN_TOKEN = your_admin_token
@USER_TOKEN = your_user_token

### 4. Get ADMIN files (should work)
GET {{URL}}/user/1/mydrive
Authorization: Bearer {{ADMIN_TOKEN}}
Accept: application/json

### 5. Get USER files (should work)
GET {{URL}}/user/2/mydrive
Authorization: Bearer {{USER_TOKEN}}
Accept: application/json

### 6. USER trying to access ADMIN files (should FAIL with 403)
GET {{URL}}/user/1/mydrive
Authorization: Bearer {{USER_TOKEN}}
Accept: application/json

### 7. Access files WITHOUT token (should FAIL with 401)
GET {{URL}}/user/1/mydrive
Accept: application/json

### 8. Download ADMIN file (should work)
GET {{URL}}/user/1/mydrive/1/download
Authorization: Bearer {{ADMIN_TOKEN}}

### 9. Download USER file (should work)
GET {{URL}}/user/2/mydrive/7/download
Authorization: Bearer {{USER_TOKEN}}

### 10. USER trying to download ADMIN file (should FAIL with 403)
GET {{URL}}/user/1/mydrive/1/download
Authorization: Bearer {{USER_TOKEN}}


### 11. USER trying to download folder as zip
GET {{URL}}/user/2/mydrive/6/downloadfolder
Authorization: Bearer {{USER_TOKEN}}
Accept: application/zip

### 12. Admin trying to download multiple files as zip (POST)
POST {{URL}}/user/1/mydrive/download/multiple
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json
Accept: application/zip
[1, 2, 4]


###
PUT {{URL}}/user/1/mydrive/1/rename
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json
Accept: application/json
"test1.html"



### === Error Testing ===

### 1. Wrong password (should FAIL)
POST {{URL}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpassword"
}

### 2. Non-existent user (should FAIL)
POST {{URL}}/auth/login
Content-Type: application/json

{
  "username": "hacker",
  "password": "password123"
}

### 3. Duplicate registration (should FAIL)
POST {{URL}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "email": "duplicate@test.com",
  "password": "password123"
}